added readme for how to run the tests
keycloak/keycloak-nodejs-admin-client pull request #309
Opened 2021-11-22 13:21 UTC by edewit

and removed `DEBUG` env var

2021-11-22 17:13 UTC, jonkoops approved these changes

2021-11-22 17:13 UTC, jonkoops commented on README.md
> +To build the source do a build:
This sentence seems a bit strange, perhaps something like:
```suggestion
To build from source run the following command:
```

2021-11-22 17:13 UTC, jonkoops commented on README.md
> +Start keycloak in a docker container or run it locally:
```suggestion
Start Keycloak in a Docker container or run it locally:
```

2021-11-22 19:47 UTC, ssilvert requested changes
Please add that to run the tests you need Keycloak on 8080 and you need an admin user on master realm with username/password as wwwy3y3/wwwy3y3.

2021-11-22 19:49 UTC, ssilvert approved these changes

2021-11-24 15:08 UTC, jonkoops approved these changes

2021-11-24 15:08 UTC, merged