added CRUD authorization scope functions
keycloak/keycloak-nodejs-admin-client pull request #348
Opened 2021-12-21 14:17 UTC by edewit

CRUD authorization scopes

2021-12-21 22:32 UTC, jonkoops requested changes

2021-12-21 22:32 UTC, jonkoops commented on test/clients.spec.ts
> +    it('create scope', async () => {});
This test is empty

2021-12-22 07:10 UTC, edewit commented on test/clients.spec.ts
> +    it('create scope', async () => {});
oops yes I moved it...

2021-12-22 09:28 UTC, merged

2021-12-22 18:44 UTC, jonkoops commented
LGTM