Add support for generating IdToken and UserInfo example payloads (#411)
keycloak/keycloak-nodejs-admin-client pull request #412
Opened 2022-02-12 12:21 UTC by thomasdarimont

Fixes #411

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

2022-02-14 19:21 UTC, ssilvert commented
Also related to https://github.com/keycloak/keycloak-admin-ui/issues/1564

2022-02-14 19:33 UTC, jonkoops requested changes

2022-02-14 19:33 UTC, jonkoops commented on src/resources/clients.ts
> +  object
According to the source the return type for this one is `Map<String, Object>`, so we can use a more narrow type here in TypeScript as well.
```suggestion
  Record<string, unknown>
```

2022-02-14 19:33 UTC, jonkoops commented on src/resources/clients.ts
> +  object
This method seems to return a type of [`IdToken`](https://www.keycloak.org/docs-api/16.1/rest-api/index.html#_idtoken), let's make this reflect that.

2022-02-14 21:12 UTC, thomasdarimont commented
@jonkoops thanks for taking a look, how about returning Record<string, unknown> from both methods and add the more precise type information later?

I started to create the proper type definitions for JsonWebToken, IDToken, AccessToken and UserInfo - saved those in [this gist](https://gist.github.com/thomasdarimont/d8272edb303bda2d1ddfc93a26512a5a).
I was not sure whether this was necessary as there is already `AccessTokenRepresentation.ts`. Perhaps you can take it from there :)

2022-03-23 12:05 UTC, jonkoops commented
@thomasdarimont could you give this PR a rebase? Our CI was borked for a while but should be good now.

2022-03-23 13:16 UTC, thomasdarimont commented
@jonkoops thanks for the feedback. I just rebased and updated the PR. I noticed that we now already have a `evaluateGenerateIdToken` and `evaluateGenerateUserInfo` function.

The only effective change this PR brings is changing the return type from `object` to `Record<string, unknown>` which might require projects to change code.

Hence, I think this PR is obsolete now and can be closed.

2022-03-23 15:35 UTC, merged